### ISSUE TITLE
Make hb-stack to deploy stack.yml or docker-compose.yml files in the same manner

### ISSUE THREAD

**Issue by adrianharabula** [richard-fairthorne/hb-helpers#1]
Say we have the following `stack.yml`
```
version: '3'

services:
  db:
    image: mongo:3.6

  backend:
    image: nginx:latest
    ports:
      - 80:80
```
By adding at the top
```
#!hb-stack deploy myapp
```
Will execute
```
docker stack deploy -c stack.yml myapp
```

And will make the app running.

Alternatively can be made to use `docker-compose` instead. The command to get project up and running will be:
```
docker-compose up -d
```
